/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Billing;

/**
 *
 * @author Fazal
 */
public class BillingSystem extends javax.swing.JFrame {

   String operations;
   String answer;
   double firstnum,secondnum,result;
   
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bmin = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bans = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bperc = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bmulti = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bclr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 360));
        jPanel1.setLayout(null);

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jPanel1.add(txtDisplay);
        txtDisplay.setBounds(20, 20, 290, 50);

        b8.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(60, 50));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(90, 80, 60, 50);

        b7.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(60, 50));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(20, 80, 60, 50);

        b9.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(60, 50));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(180, 80, 60, 50);

        badd.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        badd.setText("+");
        badd.setPreferredSize(new java.awt.Dimension(60, 50));
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(250, 80, 60, 50);

        b5.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(60, 50));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(90, 140, 60, 50);

        b4.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(60, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(20, 140, 60, 50);

        b6.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(60, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(180, 140, 60, 50);

        bmin.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bmin.setText("-");
        bmin.setPreferredSize(new java.awt.Dimension(60, 50));
        bmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminActionPerformed(evt);
            }
        });
        jPanel1.add(bmin);
        bmin.setBounds(250, 140, 60, 50);

        b2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(60, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(90, 200, 60, 50);

        b1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(60, 50));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(20, 200, 60, 50);

        bans.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bans.setText("=");
        bans.setPreferredSize(new java.awt.Dimension(60, 50));
        bans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bansActionPerformed(evt);
            }
        });
        jPanel1.add(bans);
        bans.setBounds(180, 310, 130, 40);

        bdot.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bdot.setText(".");
        bdot.setPreferredSize(new java.awt.Dimension(60, 50));
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        jPanel1.add(bdot);
        bdot.setBounds(90, 260, 60, 50);

        bperc.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bperc.setText("%");
        bperc.setPreferredSize(new java.awt.Dimension(60, 50));
        bperc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpercActionPerformed(evt);
            }
        });
        jPanel1.add(bperc);
        bperc.setBounds(180, 260, 60, 50);

        b3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(60, 50));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(180, 200, 60, 50);

        bmulti.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bmulti.setText("*");
        bmulti.setPreferredSize(new java.awt.Dimension(60, 50));
        bmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmultiActionPerformed(evt);
            }
        });
        jPanel1.add(bmulti);
        bmulti.setBounds(250, 200, 60, 50);

        bdiv.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bdiv.setText("/");
        bdiv.setPreferredSize(new java.awt.Dimension(60, 50));
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv);
        bdiv.setBounds(250, 260, 60, 50);

        b0.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        b0.setText("0");
        b0.setPreferredSize(new java.awt.Dimension(60, 50));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(20, 260, 60, 50);

        bclr.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bclr.setText("CE");
        bclr.setPreferredSize(new java.awt.Dimension(60, 50));
        bclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclrActionPerformed(evt);
            }
        });
        jPanel1.add(bclr);
        bclr.setBounds(20, 310, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 48, 330, 360);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(930, 370));
        jPanel3.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jCheckBox1.setText("Roll");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(20, 280, 130, 49);

        jCheckBox2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jCheckBox2.setText("Fruits");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(20, 40, 130, 49);

        jCheckBox3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jCheckBox3.setText("Burger");
        jCheckBox3.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(20, 220, 130, 49);

        jCheckBox4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jCheckBox4.setText("Veg");
        jCheckBox4.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(20, 100, 130, 49);

        jCheckBox5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jCheckBox5.setText("Pizza");
        jCheckBox5.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox5);
        jCheckBox5.setBounds(20, 160, 130, 49);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(140, 50, 100, 40);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jPanel3.add(jTextField2);
        jTextField2.setBounds(140, 110, 100, 40);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel3.add(jTextField3);
        jTextField3.setBounds(140, 170, 100, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jPanel3.add(jTextField4);
        jTextField4.setBounds(140, 230, 100, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel3.add(jTextField5);
        jTextField5.setBounds(140, 290, 100, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(630, 330));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Total Cost");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 30, 210, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Total Delivery Cost");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 80, 260, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Total Cost Mileage");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 130, 260, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("CGST");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 210, 160, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("SGST");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 260, 190, 30);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jPanel2.add(jTextField6);
        jTextField6.setBounds(450, 30, 110, 40);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jPanel2.add(jTextField7);
        jTextField7.setBounds(450, 80, 110, 40);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jPanel2.add(jTextField8);
        jTextField8.setBounds(450, 130, 110, 40);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jPanel2.add(jTextField9);
        jTextField9.setBounds(450, 210, 110, 40);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(450, 260, 110, 40);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(250, 30, 630, 330);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(380, 40, 890, 370);

        jPanel5.setPreferredSize(new java.awt.Dimension(1250, 110));
        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("SubTotal");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(220, 0, 120, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setText("Tax");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(220, 30, 120, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel8.setText("Total Amount");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(220, 60, 180, 30);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Rs 0.0");
        jPanel5.add(jTextField11);
        jTextField11.setBounds(560, 0, 310, 30);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs 0.0");
        jPanel5.add(jTextField12);
        jTextField12.setBounds(560, 30, 310, 30);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Rs 0.0");
        jPanel5.add(jTextField13);
        jTextField13.setBounds(560, 60, 310, 30);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(910, 10, 150, 38);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(910, 50, 158, 38);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 420, 1240, 100);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        jLabel9.setText("Online Billing System");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, -10, 430, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        String EnterNumber = txtDisplay.getText() +b5.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b5ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
      if(!txtDisplay.getText().contains("."))
      {
          txtDisplay.setText(txtDisplay.getText() + bdot.getText());
      }
    }//GEN-LAST:event_bdotActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
         String EnterNumber = txtDisplay.getText() +b7.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
         String EnterNumber = txtDisplay.getText() +b8.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b8ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        String EnterNumber = txtDisplay.getText() +b0.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b0ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
         String EnterNumber = txtDisplay.getText() +b6.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b6ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        String EnterNumber = txtDisplay.getText() +b9.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        String EnterNumber = txtDisplay.getText() +b4.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
   String EnterNumber = txtDisplay.getText() +b1.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         String EnterNumber = txtDisplay.getText() +b2.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String EnterNumber = txtDisplay.getText() +b3.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b3ActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_baddActionPerformed

    private void bminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminActionPerformed
         firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_bminActionPerformed

    private void bmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmultiActionPerformed
         firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_bmultiActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
       firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_bdivActionPerformed

    private void bpercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpercActionPerformed
         firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "%";
    }//GEN-LAST:event_bpercActionPerformed

    private void bclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclrActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_bclrActionPerformed

    private void bansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bansActionPerformed
      secondnum = Double.parseDouble(txtDisplay.getText());
      if(operations== "+")
      {
          result = firstnum + secondnum;
          answer = String.format("%.2f",result);
          txtDisplay.setText(answer);
      }
     
       else if(operations== "-")
      {
          result = firstnum - secondnum;
          answer = String.format("%.2f",result);
          txtDisplay.setText(answer);
      }
       else if(operations== "*")
      {
          result = firstnum * secondnum;
          answer = String.format("%.2f",result);
          txtDisplay.setText(answer);
      }
       else if(operations== "/")
      {
          result = firstnum / secondnum;
          answer = String.format("%.2f",result);
          txtDisplay.setText(answer);
      }
      else
       {
           result = firstnum % secondnum;
          answer = String.format("%.2f",result);
          txtDisplay.setText(answer);
           
       }
      
    }//GEN-LAST:event_bansActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
      if(jCheckBox2.isSelected())
      {
          jTextField1.setEditable(true);
          jTextField1.setText("");
          jTextField1.requestFocus();
      }
      else
      {
          jTextField1.setEditable(false);
          jTextField1.setText("0");
      }   
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtDisplay.setText("");
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        jTextField7.setText("0");
        jTextField8.setText("0");
        jTextField9.setText("0");
        jTextField10.setText("0");
        jTextField11.setText("Rs. 0.00");
        jTextField12.setText("Rs. 0.00");
        jTextField13.setText("Rs. 0.00");
       
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
       if(jCheckBox4.isSelected())
      {
          jTextField2.setEditable(true);
          jTextField2.setText("");
          jTextField2.requestFocus();
      }
      else
        {
          jTextField2.setEditable(false);
          jTextField2.setText("0");
          
    }   
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(jCheckBox5.isSelected())
      {
          jTextField3.setEditable(true);
          jTextField3.setText("");
          jTextField3.requestFocus();
      }
      else
        {
          jTextField3.setEditable(false);
          jTextField3.setText("0");
          
    }   
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if(jCheckBox3.isSelected())
      {
          jTextField4.setEditable(true);
          jTextField4.setText("");
          jTextField4.requestFocus();
      }
      else
        {
          jTextField4.setEditable(false);
          jTextField4.setText("0");
          
    }   
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         if(jCheckBox1.isSelected())
      {
          jTextField5.setEditable(true);
          jTextField5.setText("");
          jTextField5.requestFocus();
      }
      else
        {
          jTextField5.setEditable(false);
          jTextField5.setText("0");
          
    }   
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) || (jCheckBox3.isSelected())  || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()))
        {
           double f = Double.parseDouble(jTextField1.getText()) * 50;
           double v = Double.parseDouble(jTextField2.getText()) * 80;
           double p = Double.parseDouble(jTextField3.getText()) * 200;
           double b = Double.parseDouble(jTextField4.getText()) * 250;
           double r = Double.parseDouble(jTextField5.getText()) * 100;
           
           double totalitems = f + v + p + b + r;
           double del = totalitems * 5/100;
           double mill = del * 2/100;
           
           double subtotal = totalitems + del + mill;
           double cgst = subtotal * 14/100;
           double sgst = cgst;
           
           double tax = cgst + sgst;
           double amount = tax + subtotal;
           
           
           String items = String.format("%.2f",totalitems);
           jTextField6.setText((String)items);
           
           String d = String.format("%.2f",del);
           jTextField7.setText((String)d);
           
           String m = String.format("%.2f",mill);
           jTextField8.setText((String)m);
           
           String c = String.format("%.2f",cgst);
           jTextField9.setText((String)c);
           
           String s = String.format("%.2f",sgst);
           jTextField10.setText((String)s);
           
           String sub = String.format("%.2f",subtotal);
           jTextField11.setText((String)sub);
           
           String t = String.format("%.2f",tax);
           jTextField12.setText((String)t);
           
           String ta = String.format("%.2f",amount);
           jTextField13.setText((String)ta);
           
        }
        else
        {
            txtDisplay.setText("Enter choice");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bans;
    private javax.swing.JButton bclr;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bmin;
    private javax.swing.JButton bmulti;
    private javax.swing.JButton bperc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
